### ISSUE TITLE
Refactore Gloses.yaml

### ISSUE THREAD

**Issue by Krolov18** [Krolov18/PFMG#39]
Gloses dissocie en source vs destination. Seulement les gloses au final, doivent être représentées dans un dictionnaire ayant en clés les POS et en valeurs les sigmas. On augmente aussi cette structure des alignements entre source et destination.

```yaml
source: # Français
  D:
    Genre: [ m, f ]
    Nombre: [ sg, pl ]
  NOM:
    Genre: [ m, f ]
    Nombre: [ sg, pl ]
destination: # Kalaba
  D:
    Genre: [ m, f, n ]
    Nombre: [ sg, pl ]
  NOM:
    Cf: [ n1, n2 ]
    Genre: [ m, f, n ]
    Nombre: [ sg, pl ]
```

Dans cette nouvelle structure, le noeud le plus haut est le POS et les intermédiaires (source et destination) sont augmentés de `alignment` qui est là pour restreindre les cases du paradigmes.
```yaml
N:
  source:
    Genre: [ m, f ]
    Nombre: [ sg, pl ]
  destination:
    Genre: [ a, b, c, d ]
    Nombre: [ sg, du, pl ]
  alignment:
    Genre=m: [ Genre=a, Genre=d ]
    Genre=f: [ Genre=b, Genre=c ]
    Nombre=sg: [ Nombre=sg ]
    Nombre=pl: [ Nombre=du, Nombre=pl ]
```

le champ `alignment` permet de contrôler les liens morphosyntaxiques entre source et destination. Si je commente l'exemple ci-dessus, s'il y a du singulier dans la forme en français alors la forme en kalaba sera aussi singulier. Si la forme est masculine en français alors elle sera ambigue entre le genre a et d en kalaba.
