### ISSUE TITLE
Ajoute `alignment` à gloses.yaml

### ISSUE THREAD

**Issue by Krolov18** [Krolov18/PFMG#41]
`alignment` permet de réduire l'ambiguité entre la langue source et la langue de destination.

```yaml
source: # Français
  D:
    Genre: [ m, f ]
    Nombre: [ sg, pl ]
  NOM:
    Genre: [ m, f ]
    Nombre: [ sg, pl ]
destination: # Kalaba
  D:
    Genre: [ m, f, n ]
    Nombre: [ sg, pl ]
  NOM:
    Cf: [ n1, n2 ]
    Genre: [ a, b, c, d ]
    Nombre: [ sg, pl ]
alignment:
  N:
    Genre=m: [ Genre=a, Genre=d ]
    Genre=f: [ Genre=b, Genre=c ]
    Nombre=sg: [ Nombre=sg ]
    Nombre=pl: [ Nombre=du, Nombre=pl ]
```

le champ `alignment` permet de contrôler les liens morphosyntaxiques entre source et destination. Si je commente l'exemple ci-dessus, s'il y a du singulier dans la forme en français alors la forme en kalaba sera aussi singulier. Si la forme est masculine en français alors elle sera ambiguë entre le genre "a" et "d" en kalaba. Cela
