### ISSUE TITLE
Refactore Blocks.yaml

### ISSUE THREAD

**Issue by Krolov18** [Krolov18/PFMG#42]
De manière similaire  à `Gloses.yaml`, `Blocks.yaml` n'est pas correctement structuré. La base des noeuds du fichiers devraient être les POS et non source/destination

La structure suivante :
```yaml
source:
  D:
    - Nombre=pl: X2?X2:X+s
  NOM:
    - Nombre=pl: X2?X2:X+s
destination:
  D:
    - Genre=m: X+o
      Genre=f: X+i
      Genre=n: X+e
    - Nombre=sg: X+s
      Nombre=pl: X+j
  NOM:
    - Cf=n1,Nombre=sg: X+v
      Cf=n1,Nombre=pl: X+l
      Cf=n2,Nombre=sg: X+j
      Cf=n2,Nombre=pl: X+g
```

devrait être formattée comme :

```yaml
D:
  source:
    - Nombre=pl: X2?X2:X+s
  destination:
    - Genre=m: X+o
      Genre=f: X+i
      Genre=n: X+e
    - Nombre=sg: X+s
      Nombre=pl: X+j
NOM:
  source:
    - Nombre=pl: X2?X2:X+s
  destination:
    - Cf=n1,Nombre=sg: X+v
      Cf=n1,Nombre=pl: X+l
      Cf=n2,Nombre=sg: X+j
      Cf=n2,Nombre=pl: X+g
```

Comme dans `Gloses.yaml` la structure de données utilisées est un dictionnaire qui a pour premier niveau de clés, les POS.
