### ISSUE TITLE
feature : MorphoSyntax.yaml - Ajouter l'optionalité/duplication de composants

### ISSUE THREAD

**Issue by Krolov18** [Krolov18/PFMG#80]
```yaml
start: "S"

NP:
  Source:
    Syntagmes:
      - [ "D", "N" ]
    Accords:
      - "Genre,Nombre"
    Percolation:
      - "Genre,Nombre"
    Traduction:
      - [ 1, 0 ]
  Destination:
    Syntagmes:
      - [ "N", "D" ]
    Accords:
      - "Genre,Nombre"
    Percolation:
      - "Genre,Nombre"
```

Dans cet exemple minimaliste, un NP se compose d'un D suivi d'un N. Comment faisons nous pour reconnaître à la fois `D N` et `N`. La facilité serait d'écrire deux règles distinctes. On peut néanmoins simplifier les choses. Si dans la langue source `D` est optionnel mais que dans la langue cible cet élément est obligatoire alors notre alignement initial est cassé car dans l'implémentation en cours, les composants ne peuvent pas apparaître de nulle part. Ils peuvent disparaître, ils peuvent être dupliqués mais pas apparaître, ainsi la règle de transformation suivante n'est pas possible en l'état actuel.

`D? N -> N D`

Une solution au problème serait que dans ce genre de situation, tout `D` dans la langue cible peut avoir cette place tant qu'elle respecte les règles d'accord bien évidemment. Cette solution présuppose un alignement qui dirait'si je n'ai pas de D dans source et que D est obligatoire dans cible, alors tout D dans cible peut prendre cette place'.

Du coup comment ferait on si nous avons :

`D N -> L K`

Pourquoi ajouter ces contraintes à Gloses.yaml ?
